client/.eslintrc.json, client/package-lock.json, client/package.json, client/src/registerServiceWorker.js, package-lock.json
=> Added stylelint and proptypes packages

client/src/components/CellResponses/Cell/Cell.css, client/src/components/CellResponses/Cell/Cell.jsx, client/src/components/CellResponses/CellResponses.css, client/src/components/CellResponses/CellResponses.jsx
=> finished cell text responses

client/src/App.jsx, client/src/components/Dashboard/ClassBox/ClassBox.css, client/src/components/Dashboard/ClassBox/ClassBox.jsx
=> Dashboard to Units completed

client/src/App.jsx, client/src/components/Survey/Back/Back.jsx, client/src/components/Survey/Survey.jsx, client/src/components/Units/Units.jsx
Back buttons now work on the survey and units page. Routing works. Fixed #22
=> Finished up the back button routing

client/src/components/Units/Units.jsx
=> Finished Unit to Survey route

client/src/components/Units/Units.jsx
=> fixed back button on units page

client/src/components/CellResponses/Cell/Cell.jsx, client/src/components/CellResponses/CellResponses.jsx, client/src/components/Dashboard/ClassBox/ClassBox.jsx, client/src/components/Dashboard/Dashboard.jsx
=> fixed style for dashboard

client/.eslintrc.json, client/src/components/Survey/MC/MC.jsx, client/src/components/Survey/Star/Star.css, client/src/components/Survey/Star/Star.jsx
created a new branch and fixed styling for Survey components on it.
=> finished styling on new branch for survey

client/src/components/Lessons/LessonBox/LessonBox.jsx, client/src/components/Lessons/Lessons.jsx
=> Added back button and correct navlink for lessons

client/src/components/LessonReflection/LessonReflection.css, client/src/components/LessonReflection/LessonReflection.jsx, server/routes/index.js
add font size and color options to mce editor
=> Tinymce updates

client/src/components/Units/Unitbox.css, client/src/components/Units/Units.css
changed the margins to % and widths to constants (px)
=> fixed alignments

client/src/components/Lessons/Modal/AddLessonModal.jsx
=> re-add onDrop method, fixes addModal

client/src/components/Lessons/Lessons.jsx
=> add back AddlessonBox onClick prop

client/src/components/Dashboard/AddClassBox/AddClassBox.css, client/src/components/Dashboard/AddClassBox/AddClassBox.jsx
=> fixed links between the student and class modals

server/db/portal.sql
=> fixed sql tables

client/src/App.jsx, client/src/components/Dashboard/ClassBox/ClassBox.jsx, client/src/components/Units/Unitbox.jsx, client/src/components/Units/Units.jsx
=> Fixed routes for classes and units

client/src/components/Lessons/AddLessonBox/AddLessonBox.jsx
fixes #100 
ESLint wants a onKeyDown function, but it has the same functionality as the onClick function, so I just added in 1 function for the both of them.
=> removed unneeded function

client/src/components/Dashboard/AddClassBox/AddClassBox.css, client/src/components/Dashboard/AddClassBox/AddClassBox.jsx, client/src/components/Units/Units.jsx
=> Unit fetching and buttons

client/src/components/Dashboard/AddClassBox/AddClassBox.css, client/src/components/Dashboard/AddClassBox/AddClassBox.jsx, client/src/components/Lessons/Lessons.css, client/src/components/Lessons/Modal/AddLessonModal.css, client/src/components/Lessons/Modal/AddLessonModal.jsx, client/src/components/Units/Units.css, server/routes/index.js
=> fixed buttons 'leaking' from modal container

client/package.json, client/src/App.jsx, client/src/components/LessonReflection/LessonReflection.jsx, client/src/components/Lessons/Lessons.jsx, client/src/components/Survey/Survey.css, client/src/components/Units/Units.css, client/src/components/Units/Units.jsx
=> yay fixed all back buttons!

client/src/components/Histogram/Histogram.jsx, client/src/components/Survey/Survey.jsx, server/db/portal.sql, server/package-lock.json, server/routes/index.js
=> Made questions dynamic via tables and appropriate fetches

client/src/App.css, client/src/App.jsx, client/src/components/Dashboard/Dashboard.jsx, client/src/components/LessonReflection/LessonReflection.css, client/src/components/LessonReflection/LessonReflection.jsx, client/src/components/Lessons/Lessons.css, client/src/components/Lessons/Lessons.jsx, client/src/components/Units/Units.jsx, server/routes/index.js
=> Logout b gone

client/src/components/Lessons/AddLessonBox/AddLessonBox.jsx, client/src/components/Lessons/Modal/AddLessonModal.jsx
=> fixed enter press on lesson modal

client/src/components/Units/Units.jsx
=> Hitting enter on add new unit textbox send info and closes box

client/src/components/Dashboard/Dashboard.jsx
=> fixed redirect issues

client/src/App.jsx, client/src/components/Histogram/Histogram.jsx, client/src/components/Lessons/Lessons.jsx
=> fixed unitID to be dynamic

client/src/components/Dashboard/Dashboard.jsx, server/routes/index.js
=> small bug fixes

client/src/components/Dashboard/Dashboard.jsx, client/src/components/Login/Login.jsx, server/auth.js, server/routes/index.js
=> enhancements made for fetch redirects

.gitignore, client/src/App.jsx, client/src/components/Dashboard/Dashboard.jsx, client/src/components/Units/Units.jsx, server/.gitignore, server/routes/index.js
=> Redirect fix

server/package-lock.json, server/routes/index.js
=> yay fixed await

client/src/components/Histogram/Histogram.jsx, server/routes/index.js
=> Fixed hardcoded year on /survey POST yeeeee

client/src/components/Dashboard/ClassBox/ClassBox.jsx, client/src/components/Dashboard/Dashboard.jsx, client/src/components/Lessons/Lessons.jsx, client/src/components/Units/Unitbox.jsx, client/src/components/Units/Units.jsx, server/routes/auth.js, server/routes/index.js
=> Student hide

server/routes/index.js
=> fixed something the merge conflict broke

client/src/components/Units/Units.jsx
=> fixes the unit name stack (issue 182)

.gitignore, server/routes/index.js
=> at login students will only see classes and will have no teacher powers

server/routes/index.js
=> fix questions post ('text' -> 'input')

client/src/components/Dashboard/AddClassBox/AddClassBox.jsx, server/db/portal.sql, server/routes/index.js
=> Student display

client/src/components/Units/Units.jsx
=> added in hide for unit add

client/src/components/Lessons/LessonBox/LessonBox.css, client/src/components/Lessons/LessonBox/LessonBox.jsx
=> styling x button lesson page
